/*
# HTTPS-01.js
#
# This basic HTTPS server is used to verify that the TLS certificate
# and private key are correctly configured for your CCS Web Server.
#
# This is a temporary test server only.
#
# This HTTPS server is NOT required for the xstAuth Light Server (auth.yourdomain.com). The xstAuth Light Server provides its own
# functionality for handling ACME HTTP-01 challenges and for verifying HTTPS configuration under its Help menu.
*/

const fs = require('fs');
const https = require('https');

const publicdnsname = 'www.yourdomain.com';
const bind_address = '0.0.0.0';
const port = 443;

// TLS certificate and private key generated by win-acme (WACS).
const privateKeyPath = 'C:/xstAuth/certs/www.yourdomain.com-key.pem';
const certificatePath = 'C:/xstAuth/certs/www.yourdomain.com-crt.pem';

// Load the TLS certificate and private key.
const options = {
    key: fs.readFileSync(privateKeyPath),
    cert: fs.readFileSync(certificatePath)
};

// Create the HTTPS server.
const simpleserver = https.createServer(options, (req, res) => {

    res.writeHead(200, {
        'Content-Type': 'text/html'
    });

    res.end(`
        <!DOCTYPE html>
        <html>
        <head>
            <title>HTTPS Test</title>
        </head>
        <body>
            <h1>Hello from ${publicdnsname}.</h1>
            <h3>This page is being served over HTTPS on port ${port}.</h3>
            <p>
                The HTTPS server is working and the TLS certificate
                has been successfully loaded.
            </p>
        </body>
        </html>
    `);
});

// Start the HTTPS server.
simpleserver.listen(port, bind_address, () => {
    console.log(
        `Temporary HTTPS server is running on ${bind_address}:${port}.`
    );
    console.log(
        `Test URL: https://${publicdnsname}/`
    );
});

// Handle server errors.
simpleserver.on('error', (error) => {
    if (error.code === 'EADDRINUSE') {
        console.log(`Port ${port} is already in use.`);
        return;
    }
    console.error('HTTPS server error:', error);
});
